#!/bin/bash -l

#SBATCH --job-name=ACER
#SBATCH --time=24:00:00
#SBATCH --output=out.%j.%a.o
#SBATCH --error=out.%j.%a.e
#SBATCH --constraint=gpu
# #SBATCH --partition=debug

# #SBATCH --account=ch7
#SBATCH --account=s658
# #SBATCH --account=eth2

#SBATCH --array=0-49

# #SBATCH --ntasks=1
# #SBATCH --ntasks-per-node=1

# ======START=====
COMMNAME=ACER_00

SETTINGS=" --gamma 0.995 --nnl1 128 --nnl2 128 --nnFunc SoftSign  --outWeightsPrefac 0.1 --learner ACER --obsPerStep 1 --maxTotObsNum 131072 --minTotObsNum 131072  --totNumSteps 10000000 --explNoise 0.4472136 --bSampleSequences 1 --batchSize 8 --learnrate 0.0001  --targetDelay 0.005  --epsAnneal 5e-7 --nMasters 1 --nThreads 12 --ppn 2 "

MYNAME=`whoami`
SMARTIESDIR="${HOME}/smarties/"
BASEPATH="/scratch/snx3000/${MYNAME}/smarties/"
RUNTRIAL=(1 2 3 4 5)

TASKNAME=(HumanoidStandup-v2 Humanoid-v2 Ant-v2 Walker2d-v2 HalfCheetah-v2 Reacher-v2 Swimmer-v2 Hopper-v2 InvertedPendulum-v2 InvertedDoublePendulum-v2)
SHORTID=( standu             humanw      spider walker      cheeta         reachr     swimmr     hopper    invpnd              dblpnd)

cases=()
rundir=()
appspec=()
#approximatively sorted by strongest effect on runtime
for it in `seq 0 ${#TASKNAME[@]}`; do
for r in ${RUNTRIAL[@]}; do

cases+=(" ")
rundir+=("${SHORTID[$it]}_${COMMNAME}_TRIAL${r}")
appspec+=("${TASKNAME[$it]}")

done

done

# stuff that depends on SLURM_ARRAY_TASK_ID
RUNFOLDER=${rundir[$SLURM_ARRAY_TASK_ID]}

RUNPATH=${BASEPATH}${RUNFOLDER}

mkdir -p ${RUNPATH}

RUNSET=${SETTINGS}${cases[$SLURM_ARRAY_TASK_ID]}

cat <<EOF >${RUNPATH}/launchSim.sh
python3 ../Communicator_gym.py \$1 ${appspec[$SLURM_ARRAY_TASK_ID]}
EOF
cat <<EOF >${RUNPATH}/factory
Environment exec=../launchSim.sh n=1
EOF
chmod +x ${RUNPATH}/launchSim.sh

# copy over stuff
cp ${SMARTIESDIR}/makefiles/rl                             ${RUNPATH}/exec
cp ${SMARTIESDIR}/source/Communicators/Communicator.py     ${RUNPATH}/
cp ${SMARTIESDIR}/source/Communicators/Communicator_gym.py ${RUNPATH}/
cp $0                                                      ${RUNPATH}/launch.sh
#git log | head  >                                         ${RUNPATH}/gitlog.log
#git diff >                                                ${RUNPATH}/gitdif.log

cd ${RUNPATH}

export OMP_NUM_THREADS=12
export OMP_PROC_BIND=CLOSE
export OMP_PLACES=cores
export CRAY_CUDA_MPS=1

srun --ntasks 2 --overcommit --threads-per-core=2 --cpu_bind=sockets --cpus-per-task=12 --ntasks-per-node=2  ./exec ${RUNSET}

#srun  -n 2 --cpu_bind=map_cpu:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17 ./run1 & srun  -n 2 --cpu_bind=map_cpu:18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35 ./run2 & wait

# =====END====
